name: Deploy Docker CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test_Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.201
    - uses: actions/checkout@v1
    - name: Build with dotnet
      working-directory: ./github_docker_deploy
      run: dotnet build --configuration Release
    - name: Run Tests
      working-directory: ./github_docker_deploy
      run: dotnet test
  publish_to_docker:
    needs: Test_Build
    runs-on: ubuntu-latest
    steps:
    -  name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    -  name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: sk9212k/testdeploy:latest
 
  create_new_container:
    needs: publish_to_docker
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker rm -f $(docker ps -aq -f name=testdeploy)
          docker rmi $(docker images | grep 'sk9212k/testdeploy' | awk '{print $3}')
          docker pull sk9212k/testdeploy
          docker run --name testdeploy -p 5000:80 --restart=always -d sk9212k/testdeploy
      
  
